package com.ccsky.sfish.dao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadsDaoConfig;
    private final DaoConfig downloadLabelDaoConfig;
    private final DaoConfig downloadDirnameDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig quickSearchDaoConfig;
    private final DaoConfig localFavoritesDaoConfig;
    private final DaoConfig bookmarksBaoConfig;
    private final DaoConfig filterDaoConfig;

    private final DownloadsDao downloadsDao;
    private final DownloadLabelDao downloadLabelDao;
    private final DownloadDirnameDao downloadDirnameDao;
    private final HistoryDao historyDao;
    private final QuickSearchDao quickSearchDao;
    private final LocalFavoritesDao localFavoritesDao;
    private final BookmarksBao bookmarksBao;
    private final FilterDao filterDao;


    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap)

//    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap)
    {
        super(db);

        downloadsDaoConfig = daoConfigMap.get(DownloadsDao.class).clone();
        downloadsDaoConfig.initIdentityScope(type);

        downloadLabelDaoConfig = daoConfigMap.get(DownloadLabelDao.class).clone();
        downloadLabelDaoConfig.initIdentityScope(type);

        downloadDirnameDaoConfig = daoConfigMap.get(DownloadDirnameDao.class).clone();
        downloadDirnameDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        quickSearchDaoConfig = daoConfigMap.get(QuickSearchDao.class).clone();
        quickSearchDaoConfig.initIdentityScope(type);

        localFavoritesDaoConfig = daoConfigMap.get(LocalFavoritesDao.class).clone();
        localFavoritesDaoConfig.initIdentityScope(type);

        bookmarksBaoConfig = daoConfigMap.get(BookmarksBao.class).clone();
        bookmarksBaoConfig.initIdentityScope(type);

        filterDaoConfig = daoConfigMap.get(FilterDao.class).clone();
        filterDaoConfig.initIdentityScope(type);

        downloadsDao = new DownloadsDao(downloadsDaoConfig, this);
        downloadLabelDao = new DownloadLabelDao(downloadLabelDaoConfig, this);
        downloadDirnameDao = new DownloadDirnameDao(downloadDirnameDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        quickSearchDao = new QuickSearchDao(quickSearchDaoConfig, this);
        localFavoritesDao = new LocalFavoritesDao(localFavoritesDaoConfig, this);
        bookmarksBao = new BookmarksBao(bookmarksBaoConfig, this);
        filterDao = new FilterDao(filterDaoConfig, this);

        registerDao(DownloadInfo.class, downloadsDao);
        registerDao(DownloadLabel.class, downloadLabelDao);
        registerDao(DownloadDirname.class, downloadDirnameDao);
        registerDao(HistoryInfo.class, historyDao);
        registerDao(QuickSearch.class, quickSearchDao);
        registerDao(LocalFavoriteInfo.class, localFavoritesDao);
        registerDao(BookmarkInfo.class, bookmarksBao);
        registerDao(Filter.class, filterDao);
    }
    
    public void clear() {
        downloadsDaoConfig.getIdentityScope().clear();
        downloadLabelDaoConfig.getIdentityScope().clear();
        downloadDirnameDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        quickSearchDaoConfig.getIdentityScope().clear();
        localFavoritesDaoConfig.getIdentityScope().clear();
        bookmarksBaoConfig.getIdentityScope().clear();
        filterDaoConfig.getIdentityScope().clear();
    }

    public DownloadsDao getDownloadsDao() {
        return downloadsDao;
    }

    public DownloadLabelDao getDownloadLabelDao() {
        return downloadLabelDao;
    }

    public DownloadDirnameDao getDownloadDirnameDao() {
        return downloadDirnameDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public QuickSearchDao getQuickSearchDao() {
        return quickSearchDao;
    }

    public LocalFavoritesDao getLocalFavoritesDao() {
        return localFavoritesDao;
    }

    public BookmarksBao getBookmarksBao() {
        return bookmarksBao;
    }

    public FilterDao getFilterDao() {
        return filterDao;
    }

}
